@QFile();
@QFile(const QString& name);
QString name() const;
void setName(const QString& name);
bool exists() const;
bool remove();
virtual bool open(int m);
bool open(int m, int f);
virtual void close();
virtual void flush();
virtual uint size() const;
virtual bool atEnd() const;
virtual long readLine(char* p, ulong maxlen);
long readLine(QString& s, ulong maxlen);
virtual int getch();
virtual int putch(int ch);
virtual int ungetch(int ch);
int handle() const;
QString errorString() const;
