@QSqlSelectCursor(const QString& query=QString::null, QSqlDatabase* db=0);
bool exec(const QString& query);
bool select();
QVariant value(int i) const;
QVariant value(const QString& name) const;
bool isNull(int i) const;
bool isNull(const QString& name) const;
QSqlError* lastError() const;
bool isValid() const;
bool isActive() const;
int at() const;
QString lastQuery() const;
int size() const;
bool isForwardOnly() const;
void setForwardOnly(bool forward);
bool seek(int i, bool relative=false);
bool next();
bool prev();
bool first();
bool last();
void changePos(const QString& name, int newPos=0);
void setOrder(const QStringList& order);
